export const columns = [
  { title: "Code", dataKey: "code" },
  { title: "Name", dataKey: "name" },
  { title: "Group", dataKey: "group" },
  { title: "Barcode", dataKey: "barcodeList" },
  { title: "Cost", dataKey: "cost" },
  { title: "Sale price before tax", dataKey: "Sale_price_before_tax" },
  { title: "Taxes", dataKey: "taxList" },
  { title: "Sale price", dataKey: "Sale_price" },
  { title: "Active", dataKey: "Active" },
  { title: "unit of measurement", dataKey: "unit_of_measurement" },
  { title: "Created", dataKey: "Created" },
  { title: "Updated", dataKey: "Updated" },
];

export const sample_data = [
  {
    Code: 1235,
    Name: "water",
    Group: "Group1",
    Barcode: "123456789",
    Cost: 20000,
    Sale_price_before_tax: 25000,
    Taxes: 5000,
    Sale_price: 30000,
    Active: true,
    unit_of_measurement: "Liter",
    Created: "1402.6.12",
    Updated: "1402.6.12",
  },
  {
    Code: 1235,
    Name: "battrey",
    Group: "Group1",
    Barcode: "123456789",
    Cost: 20000,
    Sale_price_before_tax: 25000,
    Taxes: 5000,
    Sale_price: 30000,
    Active: true,
    unit_of_measurement: "Liter",
    Created: "1402.6.12",
    Updated: "1402.6.12",
  },
];
