export const Documentsitem_Table_columns = [
  { title: "ID", dataKey: "code" },
  { title: "Code", dataKey: "code" },
  { title: "Name", dataKey: "Name" },
  { title: "Unit of Measure", dataKey: "unit_of_Measure" },
  { title: "Quantity", dataKey: "quantity" },
  { title: "Price Before Tax", dataKey: "price_before_tax" },
  { title: "Tax", dataKey: "tax" },
  { title: "Price", dataKey: "price" },
  { title: "Price", dataKey: "price" },
  { title: "Total Before Discount", dataKey: "total_before_discount" },
  { title: "Discount", dataKey: "discount" },
  { title: "Total", dataKey: "total" },
];

export const documentItemsData = [
  {
    code: "1",
    Name: "Product A",
    unit_of_Measure: "Each",
    quantity: 10,
    price_before_tax: 50.0,
    tax: 5.0,
    price: 55.0,
    total_before_discount: 500.0,
    discount: 10.0,
    total: 490.0,
  },
  {
    code: "2",
    Name: "Product B",
    unit_of_Measure: "Each",
    quantity: 5,
    price_before_tax: 30.0,
    tax: 3.0,
    price: 33.0,
    total_before_discount: 150.0,
    discount: 5.0,
    total: 145.0,
  },
  {
    code: "3",
    Name: "Product C",
    unit_of_Measure: "Dozen",
    quantity: 2,
    price_before_tax: 20.0,
    tax: 2.0,
    price: 22.0,
    total_before_discount: 40.0,
    discount: 0.0,
    total: 40.0,
  },
  {
    code: "4",
    Name: "Product D",
    unit_of_Measure: "Each",
    quantity: 8,
    price_before_tax: 40.0,
    tax: 4.0,
    price: 44.0,
    total_before_discount: 320.0,
    discount: 8.0,
    total: 312.0,
  },
  {
    code: "5",
    Name: "Product E",
    unit_of_Measure: "Each",
    quantity: 12,
    price_before_tax: 25.0,
    tax: 2.5,
    price: 27.5,
    total_before_discount: 300.0,
    discount: 15.0,
    total: 285.0,
  },
  {
    code: "6",
    Name: "Product F",
    unit_of_Measure: "Dozen",
    quantity: 4,
    price_before_tax: 15.0,
    tax: 1.5,
    price: 16.5,
    total_before_discount: 60.0,
    discount: 5.0,
    total: 55.0,
  },
  {
    code: "7",
    Name: "Product G",
    unit_of_Measure: "Each",
    quantity: 6,
    price_before_tax: 35.0,
    tax: 3.5,
    price: 38.5,
    total_before_discount: 210.0,
    discount: 12.0,
    total: 198.0,
  },
  {
    code: "8",
    Name: "Product H",
    unit_of_Measure: "Each",
    quantity: 15,
    price_before_tax: 28.0,
    tax: 2.8,
    price: 30.8,
    total_before_discount: 420.0,
    discount: 20.0,
    total: 400.0,
  },
  {
    code: "9",
    Name: "Product I",
    unit_of_Measure: "Dozen",
    quantity: 3,
    price_before_tax: 22.0,
    tax: 2.2,
    price: 24.2,
    total_before_discount: 66.0,
    discount: 3.0,
    total: 63.0,
  },
  {
    code: "10",
    Name: "Product J",
    unit_of_Measure: "Each",
    quantity: 7,
    price_before_tax: 45.0,
    tax: 4.5,
    price: 49.5,
    total_before_discount: 315.0,
    discount: 9.0,
    total: 306.0,
  },
  {
    code: "11",
    Name: "Product K",
    unit_of_Measure: "Each",
    quantity: 3,
    price_before_tax: 60.0,
    tax: 6.0,
    price: 66.0,
    total_before_discount: 180.0,
    discount: 0.0,
    total: 180.0,
  },
  {
    code: "12",
    Name: "Product L",
    unit_of_Measure: "Dozen",
    quantity: 2,
    price_before_tax: 18.0,
    tax: 1.8,
    price: 19.8,
    total_before_discount: 36.0,
    discount: 2.0,
    total: 34.0,
  },
  // Add more data items as needed...
];
