export const columns = [
  { title: "No.", dataKey: "no" },
  { title: "Name", dataKey: "name" },
  { title: "Barcode", dataKey: "barcode" },
  { title: "Unit", dataKey: "unit" },
  { title: "Unit Price", dataKey: "unitprice" },
  { title: "Qty", dataKey: "qty" },
  { title: "Discount,vat", dataKey: "discountvat" },
  { title: "Amount", dataKey: "amount" },
];

// Sample data for 10 rows
export const sampleData = [
  {
    no: 1,
    name: "Product 1",
    barcode: "123456",
    unit: "Each",
    unitprice: 10.99,
    qty: 5,
    discountvat: "5%",
    amount: 54.95,
  },
  {
    no: 2,
    name: "Product 2",
    barcode: "789012",
    unit: "Each",
    unitprice: 8.99,
    qty: 3,
    discountvat: "3%",
    amount: 26.97,
  },
  {
    no: 3,
    name: "Product 3",
    barcode: "345678",
    unit: "Each",
    unitprice: 12.49,
    qty: 2,
    discountvat: "4%",
    amount: 24.98,
  },
  {
    no: 4,
    name: "Product 4",
    barcode: "901234",
    unit: "Each",
    unitprice: 7.75,
    qty: 8,
    discountvat: "2%",
    amount: 62.0,
  },
  {
    no: 5,
    name: "Product 5",
    barcode: "567890",
    unit: "Each",
    unitprice: 15.99,
    qty: 1,
    discountvat: "6%",
    amount: 15.99,
  },
  {
    no: 6,
    name: "Product 6",
    barcode: "234567",
    unit: "Each",
    unitprice: 9.25,
    qty: 4,
    discountvat: "3%",
    amount: 37.0,
  },
  {
    no: 7,
    name: "Product 7",
    barcode: "890123",
    unit: "Each",
    unitprice: 11.5,
    qty: 6,
    discountvat: "4%",
    amount: 69.0,
  },
  {
    no: 8,
    name: "Product 8",
    barcode: "456789",
    unit: "Each",
    unitprice: 6.75,
    qty: 7,
    discountvat: "2%",
    amount: 47.25,
  },
  {
    no: 9,
    name: "Product 9",
    barcode: "012345",
    unit: "Each",
    unitprice: 14.25,
    qty: 2,
    discountvat: "3%",
    amount: 28.5,
  },
  {
    no: 10,
    name: "Product 10",
    barcode: "678901",
    unit: "Each",
    unitprice: 13.99,
    qty: 3,
    discountvat: "5%",
    amount: 41.97,
  },
];
